// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwOAnyOkXRcsxkXCPYkyY6vKn-aJjJYdk',
    appId: '1:69463399067:web:d2cf9b302ddb853aa9043e',
    messagingSenderId: '69463399067',
    projectId: 'chataapp-50a3a',
    authDomain: 'chataapp-50a3a.firebaseapp.com',
    storageBucket: 'chataapp-50a3a.firebasestorage.app',
    measurementId: 'G-4NVKVX0VFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhcWk9a255lKvBu5llOHoRSkUR6ZgGus',
    appId: '1:69463399067:android:2c976761d7db4ccaa9043e',
    messagingSenderId: '69463399067',
    projectId: 'chataapp-50a3a',
    storageBucket: 'chataapp-50a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9CFqEo0FGcT6R-SAvjm1m4gdJJHNxSIw',
    appId: '1:69463399067:ios:5faaa980bdc9f840a9043e',
    messagingSenderId: '69463399067',
    projectId: 'chataapp-50a3a',
    storageBucket: 'chataapp-50a3a.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9CFqEo0FGcT6R-SAvjm1m4gdJJHNxSIw',
    appId: '1:69463399067:ios:5faaa980bdc9f840a9043e',
    messagingSenderId: '69463399067',
    projectId: 'chataapp-50a3a',
    storageBucket: 'chataapp-50a3a.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwOAnyOkXRcsxkXCPYkyY6vKn-aJjJYdk',
    appId: '1:69463399067:web:7dd0c36f017a5145a9043e',
    messagingSenderId: '69463399067',
    projectId: 'chataapp-50a3a',
    authDomain: 'chataapp-50a3a.firebaseapp.com',
    storageBucket: 'chataapp-50a3a.firebasestorage.app',
    measurementId: 'G-T4W0DXF8KQ',
  );
}
