// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjdO_oCgV9G551uzhl0XRkpNeRX41bMEo',
    appId: '1:483331774905:web:7ccf5328f7b43824023e68',
    messagingSenderId: '483331774905',
    projectId: 'projecttwo-e6d26',
    authDomain: 'projecttwo-e6d26.firebaseapp.com',
    storageBucket: 'projecttwo-e6d26.firebasestorage.app',
    measurementId: 'G-6NVTSFD7S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_gi-NipniycUw0VgsE7T1KSbX8kOAaeI',
    appId: '1:483331774905:android:2b377bffaaa5607f023e68',
    messagingSenderId: '483331774905',
    projectId: 'projecttwo-e6d26',
    storageBucket: 'projecttwo-e6d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHGOXmABfGwgE65Q4kcd8uq7IxIeOryY',
    appId: '1:483331774905:ios:73bd7539cbf88314023e68',
    messagingSenderId: '483331774905',
    projectId: 'projecttwo-e6d26',
    storageBucket: 'projecttwo-e6d26.firebasestorage.app',
    iosBundleId: 'com.example.sabak15Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFHGOXmABfGwgE65Q4kcd8uq7IxIeOryY',
    appId: '1:483331774905:ios:73bd7539cbf88314023e68',
    messagingSenderId: '483331774905',
    projectId: 'projecttwo-e6d26',
    storageBucket: 'projecttwo-e6d26.firebasestorage.app',
    iosBundleId: 'com.example.sabak15Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjdO_oCgV9G551uzhl0XRkpNeRX41bMEo',
    appId: '1:483331774905:web:58a2d17b47362e27023e68',
    messagingSenderId: '483331774905',
    projectId: 'projecttwo-e6d26',
    authDomain: 'projecttwo-e6d26.firebaseapp.com',
    storageBucket: 'projecttwo-e6d26.firebasestorage.app',
    measurementId: 'G-QKFDDHKB3V',
  );
}
